import { FurnitureColor, Language } from './types';

export const COLORS: Record<FurnitureColor, { label: string; hex: string; tailwind: string }> = {
  [FurnitureColor.WOOD_LIGHT]: { label: 'Light Wood', hex: '#d4b996', tailwind: 'bg-[#d4b996]' },
  [FurnitureColor.WOOD_MEDIUM]: { label: 'Medium Wood', hex: '#a67c52', tailwind: 'bg-[#a67c52]' },
  [FurnitureColor.WOOD_DARK]: { label: 'Dark Wood', hex: '#5c4033', tailwind: 'bg-[#5c4033]' },
  [FurnitureColor.GREY_LIGHT]: { label: 'Light Grey', hex: '#d1d5db', tailwind: 'bg-gray-300' },
  [FurnitureColor.GREY_DARK]: { label: 'Dark Grey', hex: '#4b5563', tailwind: 'bg-gray-600' },
  [FurnitureColor.WHITE]: { label: 'White', hex: '#ffffff', tailwind: 'bg-white border border-gray-200' },
  [FurnitureColor.BLACK]: { label: 'Black', hex: '#1f2937', tailwind: 'bg-gray-900' },
};

export const TRANSLATIONS = {
  en: {
    title: 'Marcos Home',
    slogan: 'Design that makes a difference in your home',
    start: 'Start Designing',
    lang: '🇦🇪 AR',
    tables: 'Tables',
    cabinets: 'Cabinets',
    addTable: 'Add Table',
    addCabinet: 'Add Cabinet',
    wallColor: 'Wall Color',
    summary: 'Order Summary',
    total: 'Total Price',
    orderWhatsapp: 'Order via WhatsApp',
    emptyWall: 'Your wall is empty. Add items to start designing!',
    size: 'Size',
    width: 'Width',
    meter: 'm',
    cm: 'cm',
    remove: 'Remove',
    moveLeft: 'Move Left',
    moveRight: 'Move Right',
    color: 'Color',
    cabinetFeature: 'Hidden Lighting included',
    basePrice: 'Base Price',
    // Hardware
    hardware: 'Hardware',
    hardwareNone: 'Push to Open',
    hardwareHandleGold: 'Gold Handle',
    hardwareHandleBlack: 'Black Handle',
    hardwareKnobGold: 'Gold Knob',
    hardwareKnobBlack: 'Black Knob',
    dragHint: 'Drag items to reorder',
    // Veo Features
    veoTitle: 'AI Video Animator',
    veoBtn: 'Animate with AI',
    veoUpload: 'Upload Photo',
    veoPrompt: 'Prompt (Optional)',
    veoRatio: 'Aspect Ratio',
    veoGenerate: 'Generate Video',
    veoGenerating: 'Generating Video (this may take 1-2 mins)...',
    veoClose: 'Close',
    veoSelectImg: 'Select an image first',
  },
  ar: {
    title: 'Marcos Home',
    slogan: 'تصميم يصنع الفرق في منزلك',
    start: 'ابدأ التصميم',
    lang: '🇬🇧 EN',
    tables: 'طاولات',
    cabinets: 'كبتات',
    addTable: 'إضافة طاولة',
    addCabinet: 'إضافة كبت',
    wallColor: 'لون الجدار',
    summary: 'ملخص الطلب',
    total: 'السعر الإجمالي',
    orderWhatsapp: 'اطلب عبر واتساب',
    emptyWall: 'الجدار فارغ. أضف قطعاً لبدء التصميم!',
    size: 'المقاس',
    width: 'العرض',
    meter: 'متر',
    cm: 'سم',
    remove: 'حذف',
    moveLeft: 'تحريك يمين', // RTL Logic
    moveRight: 'تحريك يسار',
    color: 'اللون',
    cabinetFeature: 'شامل إضاءة مخفية',
    basePrice: 'سعر القطعة',
    // Hardware
    hardware: 'الإكسسوارات',
    hardwareNone: 'بدون مقبض (ضغط)',
    hardwareHandleGold: 'مقبض ذهبي',
    hardwareHandleBlack: 'مقبض أسود',
    hardwareKnobGold: 'مسكة ذهبية',
    hardwareKnobBlack: 'مسكة سوداء',
    dragHint: 'اسحب القطع لتغيير الترتيب',
    // Veo Features
    veoTitle: 'محرك الفيديو الذكي',
    veoBtn: 'تحريك ذكي',
    veoUpload: 'رفع صورة',
    veoPrompt: 'وصف الحركة (اختياري)',
    veoRatio: 'أبعاد الفيديو',
    veoGenerate: 'إنشاء فيديو',
    veoGenerating: 'جاري إنشاء الفيديو (قد يستغرق دقيقة)...',
    veoClose: 'إغلاق',
    veoSelectImg: 'يرجى اختيار صورة أولاً',
  }
};

export const WHATSAPP_NUMBER = "96500000000"; // Placeholder number