import React,{FormEvent,useEffect,useMemo,useState} from 'react';
import {CheckCircle2,ChevronLeft,ShoppingBag,ImageOff} from 'lucide-react';
import {supabase} from './supabase';

type CatalogItem={id:string;name:string;category:string;price_without_installation:number|null;price_with_installation:number|null};
const coffeeColors=[['عسلي ماركوز هوم','/coffee/honey-wood.webp'],['أبيض وخشب فاتح','/coffee/white-lightwood.webp'],['بني وترافرتينو','/coffee/brown-travertine.webp'],['أسود وخشب فاتح','/coffee/black-lightwood.webp'],['رمادي غامق','/coffee/darkgray-chevron.webp'],['رمادي فاتح','/coffee/lightgray-chevron.webp'],['خشبي فاتح','/coffee/lightwood-chevron.webp']];
function imageFor(item:CatalogItem){if(item.name.includes('قهوة'))return '/coffee/honey-wood.webp';if(item.name.includes('الفير'))return '/fire/main-product.webp';return null}

export default function CustomerStorefront(){
 const[items,setItems]=useState<CatalogItem[]>([]),[selected,setSelected]=useState<CatalogItem|null>(null),[installation,setInstallation]=useState(true),[name,setName]=useState(''),[phone,setPhone]=useState(''),[area,setArea]=useState(''),[measurement,setMeasurement]=useState(''),[color,setColor]=useState(''),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState<{order_number:string;customer_token:string}|null>(null),[category,setCategory]=useState('الكل');
 useEffect(()=>{supabase.from('mh2_catalog').select('id,name,category,price_without_installation,price_with_installation').eq('active',true).order('sort_order').then(({data})=>{setItems((data||[]) as CatalogItem[]);if(data?.length)setSelected(data[0] as CatalogItem)})},[]);
 const categories=useMemo(()=>['الكل',...Array.from(new Set(items.map(i=>i.category)))],[items]);
 const shown=category==='الكل'?items:items.filter(i=>i.category===category);
 const price=selected?(installation?selected.price_with_installation:selected.price_without_installation):null;
 const choose=(item:CatalogItem)=>{setSelected(item);if(item.name.includes('قهوة')&&!color)setColor('عسلي ماركوز هوم');setTimeout(()=>document.getElementById('order-form')?.scrollIntoView({behavior:'smooth',block:'start'}),120)};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;setBusy(true);setError('');const{data,error}=await supabase.rpc('mh2_create_customer_order',{p_customer_name:name,p_customer_phone:phone,p_area:area,p_service_type:selected.name,p_measurement:measurement,p_color:color,p_installation:installation,p_notes:notes});if(error||!data?.[0]){setError('تعذر تسجيل الطلب. حاول مرة أخرى.');setBusy(false);return}setDone(data[0]);setBusy(false)};
 if(done){const link=`${window.location.origin}/order/customer/${done.customer_token}`;return <main className="shop-shell" dir="rtl"><section className="shop-success"><CheckCircle2 size={58}/><h1>تم تسجيل طلبك</h1><p>رقم الطلب <b>{done.order_number}</b></p><a href={link}>متابعة الطلب الآن</a><small>احتفظ بالرابط لمتابعة حالة الطلب.</small></section></main>}
 return <main className="shop-shell" dir="rtl"><header className="shop-header"><div className="shop-logo">MH</div><div><strong>ماركوز هوم</strong><small>تصاميم وديكور — الكويت</small></div></header><section className="shop-hero"><span>Marco’s Home</span><h1>اختار التصميم اللي يناسب بيتك</h1><p>شاهد التصميم والسعر، اختر اللون وطريقة التنفيذ، ثم سجّل الطلب مباشرة. كل طلب يحصل على رابط متابعة خاص.</p></section>
 <section className="shop-catalog"><div className="category-tabs">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="visual-grid">{shown.map(item=>{const img=imageFor(item);return <article className={selected?.id===item.id?'visual-card selected':'visual-card'} key={item.id}>{img?<div className="card-photo"><img src={img} alt={item.name}/><span>{item.category}</span></div>:<div className="card-photo no-photo"><ImageOff size={34}/><strong>الصورة الأصلية قيد الإضافة</strong><small>لن نعرض صورة غير معتمدة</small><span>{item.category}</span></div>}<div className="card-body"><h3>{item.name}</h3><div className="prices"><b>{item.price_without_installation!=null?`${item.price_without_installation} د.ك`:'حسب الطلب'}<small> بدون تركيب</small></b><b>{item.price_with_installation!=null?`${item.price_with_installation} د.ك`:'حسب الطلب'}<small> مع التركيب</small></b></div><button onClick={()=>choose(item)}>اختيار هذا التصميم <ChevronLeft size={17}/></button></div></article>})}</div></section>
 {selected?.name.includes('قهوة')&&<section className="coffee-gallery"><div><h2>ألوان ركن القهوة</h2><p>اضغط على اللون لاختياره للطلب.</p></div><div className="coffee-color-grid">{coffeeColors.map(([label,img])=><button key={label} className={color===label?'selected':''} onClick={()=>setColor(label)}><img src={img} alt={label}/><span>{label}</span></button>)}</div></section>}
 <section className="shop-order-wrap" id="order-form"><form className="shop-form" onSubmit={submit}><div className="form-title"><ShoppingBag size={22}/><div><h2>تأكيد الطلب</h2><p>بيانات بسيطة فقط لإرسال الطلب للوحة ماركوز هوم.</p></div></div>{selected&&<div className="shop-selected"><strong>{selected.name}</strong><span>{price==null?'السعر يحدد بعد المراجعة':`${price} د.ك`}</span></div>}<div className="shop-install"><button type="button" className={installation?'selected':''} onClick={()=>setInstallation(true)}>مع التركيب</button><button type="button" className={!installation?'selected':''} onClick={()=>setInstallation(false)}>بدون تركيب</button></div><div className="customer-grid"><label>الاسم<input required value={name} onChange={e=>setName(e.target.value)} placeholder="اسم العميل"/></label><label>رقم الهاتف<input required inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="رقم الهاتف"/></label><label>المنطقة<input value={area} onChange={e=>setArea(e.target.value)} placeholder="مثال: حولي"/></label><label>المقاس<input value={measurement} onChange={e=>setMeasurement(e.target.value)} placeholder="مثال: عرض 4 متر"/></label><label>اللون<input value={color} onChange={e=>setColor(e.target.value)} placeholder="اللون المختار"/></label></div><label>ملاحظات<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="أي تفاصيل إضافية"/></label>{error&&<div className="auth-error">{error}</div>}<button className="shop-submit" disabled={busy||!selected}>{busy?'جاري تسجيل الطلب…':'تأكيد وإرسال الطلب'}</button></form></section></main>
}
