import React,{FormEvent,useEffect,useState} from 'react';
import {CheckCircle2,ChevronLeft,ShoppingBag} from 'lucide-react';
import {supabase} from './supabase';

type CatalogItem={id:string;name:string;category:string;price_without_installation:number|null;price_with_installation:number|null};

export default function CustomerStorefront(){
 const[items,setItems]=useState<CatalogItem[]>([]),[selected,setSelected]=useState<CatalogItem|null>(null),[installation,setInstallation]=useState(true),[name,setName]=useState(''),[phone,setPhone]=useState(''),[area,setArea]=useState(''),[measurement,setMeasurement]=useState(''),[color,setColor]=useState(''),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState<{order_number:string;customer_token:string}|null>(null);
 useEffect(()=>{supabase.from('mh2_catalog').select('id,name,category,price_without_installation,price_with_installation').eq('active',true).order('sort_order').then(({data})=>{setItems((data||[]) as CatalogItem[]);if(data?.length)setSelected(data[0] as CatalogItem)})},[]);
 const price=selected?(installation?selected.price_with_installation:selected.price_without_installation):null;
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;setBusy(true);setError('');const{data,error}=await supabase.rpc('mh2_create_customer_order',{p_customer_name:name,p_customer_phone:phone,p_area:area,p_service_type:selected.name,p_measurement:measurement,p_color:color,p_installation:installation,p_notes:notes});if(error||!data?.[0]){setError('تعذر تسجيل الطلب. حاول مرة أخرى.');setBusy(false);return}setDone(data[0]);setBusy(false)};
 if(done){const link=`${window.location.origin}/order/customer/${done.customer_token}`;return <main className="shop-shell" dir="rtl"><section className="shop-success"><CheckCircle2 size={58}/><h1>تم تسجيل طلبك</h1><p>رقم الطلب <b>{done.order_number}</b></p><a href={link}>متابعة الطلب الآن</a><small>احتفظ بالرابط لمتابعة حالة الطلب.</small></section></main>}
 return <main className="shop-shell" dir="rtl"><header className="shop-header"><div className="shop-logo">MH</div><div><strong>ماركوز هوم</strong><small>اختر التصميم وسجّل طلبك</small></div></header><section className="shop-hero"><span>Marco’s Home</span><h1>اطلب تصميمك بسهولة</h1><p>اختر الخدمة، حدّد مع أو بدون تركيب، وأدخل بياناتك. الطلب يصل مباشرة للوحة الإدارة.</p></section><section className="shop-layout"><div><h2>1. اختر الخدمة</h2><div className="shop-products">{items.map(item=><button key={item.id} className={selected?.id===item.id?'selected':''} onClick={()=>setSelected(item)}><ShoppingBag size={20}/><span><strong>{item.name}</strong><small>{item.category}</small></span><ChevronLeft size={17}/></button>)}</div></div><form className="shop-form" onSubmit={submit}><h2>2. تفاصيل الطلب</h2>{selected&&<div className="shop-selected"><strong>{selected.name}</strong><span>{price==null?'السعر يحدد بعد المراجعة':`${price} د.ك`}</span></div>}<div className="shop-install"><button type="button" className={installation?'selected':''} onClick={()=>setInstallation(true)}>مع التركيب</button><button type="button" className={!installation?'selected':''} onClick={()=>setInstallation(false)}>بدون تركيب</button></div><label>الاسم<input required value={name} onChange={e=>setName(e.target.value)} placeholder="اسم العميل"/></label><label>رقم الهاتف<input required inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="رقم الهاتف"/></label><label>المنطقة<input value={area} onChange={e=>setArea(e.target.value)} placeholder="مثال: حولي"/></label><label>المقاس<input value={measurement} onChange={e=>setMeasurement(e.target.value)} placeholder="مثال: عرض 4 متر"/></label><label>اللون<input value={color} onChange={e=>setColor(e.target.value)} placeholder="مثال: عسلي"/></label><label>ملاحظات<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="أي تفاصيل إضافية"/></label>{error&&<div className="auth-error">{error}</div>}<button className="shop-submit" disabled={busy||!selected}>{busy?'جاري تسجيل الطلب…':'تأكيد وإرسال الطلب'}</button></form></section></main>
}
