services:
  marcos-home-designer:
    build:
      context: https://github.com/Jo78855/marcos-hom.git#main
    container_name: marcos-home-designer
    restart: unless-stopped
    ports:
      - "8085:80"
