import React, { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2 } from 'lucide-react';
import { supabase } from './supabase';

type PortalData = { audience: 'customer' | 'technician'; order: { order_number: string; service_type: string; width_m: number | null; height_m: number | null; color: string | null; installation: boolean; installation_date: string | null; status: string; total?: number | null; paid_amount?: number | null; balance?: number | null }; customer: { name: string; phone?: string; area?: string | null; address?: string | null }; items: { name: string; description: string | null; quantity: number }[]; confirmations: { confirmation_type: string; accepted: boolean; rating: number | null; comment: string | null }[] };

export default function PublicOrder({ role, token }: { role: 'customer' | 'technician'; token: string }) {
  const [data, setData] = useState<PortalData | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [rating, setRating] = useState(5), [comment, setComment] = useState(''), [busy, setBusy] = useState(false), [done, setDone] = useState(false);
  const load = async () => { const { data: portal, error: portalError } = await supabase.rpc('mh_open_order_link', { raw_token: token }); if (portalError || !portal || portal.audience !== role) setError('الرابط غير صالح أو انتهت صلاحيته'); else setData(portal as PortalData); setLoading(false); };
  useEffect(() => { void load(); }, [role, token]);
  const confirmDetails = async () => { setBusy(true); const { error: confirmError } = await supabase.rpc('mh_customer_confirm_order', { raw_token: token, confirmation_kind: 'details', customer_rating: null, customer_comment: comment.trim() || null }); if (confirmError) setError('تعذر تأكيد تفاصيل الطلب.'); else { setDone(true); await load(); } setBusy(false); };
  const confirmHandover = async (event: FormEvent) => { event.preventDefault(); setBusy(true); const { error: confirmError } = await supabase.rpc('mh_customer_confirm_order', { raw_token: token, confirmation_kind: 'handover', customer_rating: rating, customer_comment: comment.trim() || null }); if (confirmError) setError('تعذر تسجيل الاستلام والتقييم.'); else { setDone(true); await load(); } setBusy(false); };
  if (loading) return <main className="public-order" dir="rtl"><div className="public-card">جاري تحميل الطلب…</div></main>;
  if (error || !data) return <main className="public-order" dir="rtl"><div className="public-card"><h1>Marco’s Home</h1><p>{error}</p></div></main>;
  const handoverReady = ['technician_done', 'awaiting_customer_handover', 'completed'].includes(data.order.status), detailsConfirmed = data.confirmations?.some(item => item.confirmation_type === 'details' && item.accepted);
  return <main className="public-order" dir="rtl"><div className="public-card"><div className="public-brand"><b>MH</b><span><strong>Marco’s Home</strong><small>{role === 'customer' ? 'متابعة طلبك' : 'مهمة التنفيذ'}</small></span></div><h1>طلب {data.order.order_number}</h1><div className="public-status">{statusLabel(data.order.status)}</div><div className="public-details"><p><span>الخدمة</span><b>{data.order.service_type}</b></p><p><span>المقاس</span><b>{measurement(data.order)}</b></p><p><span>اللون</span><b>{data.order.color || '—'}</b></p><p><span>التنفيذ</span><b>{data.order.installation ? 'مع التركيب' : 'بدون تركيب'}</b></p>{data.order.installation_date && <p><span>موعد التنفيذ</span><b>{new Date(data.order.installation_date).toLocaleString('ar-KW')}</b></p>}{role === 'customer' && <><p><span>السعر الكامل</span><b>{data.order.total == null ? 'يحدد بعد المراجعة' : `${data.order.total} د.ك`}</b></p><p><span>الدفع</span><b>{Number(data.order.balance || 0) === 0 && Number(data.order.total || 0) > 0 ? 'مدفوع بالكامل' : 'غير مدفوع'}</b></p></>}</div>{done && <div className="public-note"><CheckCircle2 size={20} /> تم تسجيل تأكيدك بنجاح.</div>}{role === 'customer' && !handoverReady && !detailsConfirmed && <div className="public-note"><textarea value={comment} onChange={e => setComment(e.target.value)} placeholder="ملاحظة اختيارية" /><button disabled={busy} onClick={() => void confirmDetails()}>{busy ? 'جاري التأكيد…' : 'تأكيد تفاصيل الطلب'}</button></div>}{role === 'customer' && handoverReady && <form className="public-note" onSubmit={confirmHandover}><strong>تأكيد استلام الأعمال</strong><label>التقييم<select value={rating} onChange={e => setRating(Number(e.target.value))}>{[5, 4, 3, 2, 1].map(value => <option key={value} value={value}>{value} من 5</option>)}</select></label><textarea value={comment} onChange={e => setComment(e.target.value)} placeholder="ملاحظتك اختيارية" /><button disabled={busy}>{busy ? 'جاري التسجيل…' : 'استلمت الأعمال'}</button></form>}{role === 'technician' && <div className="public-note">جزء الفني متوقف حاليًا كما اتفقنا.</div>}</div></main>;
}
function measurement(order: PortalData['order']) { if (order.width_m == null) return '—'; return order.height_m == null ? `${order.width_m} م` : `${order.width_m} × ${order.height_m} م`; }
function statusLabel(status: string) { return ({ draft: 'قيد المراجعة', awaiting_customer: 'بانتظار تأكيدك', confirmed: 'تم التأكيد', scheduled: 'تم تحديد الموعد', in_progress: 'قيد التنفيذ', technician_done: 'انتهى التنفيذ', awaiting_customer_handover: 'بانتظار الاستلام', completed: 'مكتمل', cancelled: 'ملغي' } as Record<string, string>)[status] || status; }
