import React, { useEffect, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { supabase } from '../supabase';

type Offer={id:number;code:string;name_ar:string;min_width:number;max_width:number|null;height_m:number;price_without_installation:number;price_with_installation:number;components_ar:string;active:boolean;sort_order:number};
type Product={id:number;code:string;category_ar:string;name_ar:string;aliases_ar:string[];description_ar:string;price_text_ar:string;details_ar:string;active:boolean;sort_order:number};

export default function AssistantAdmin(){const[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,n)=>setSession(n));return()=>data.subscription.unsubscribe()},[]);if(loading)return<main className="admin-center" dir="rtl">جاري التحميل...</main>;if(!session)return<main className="admin-login" dir="rtl"><div><div className="brand-mark">MH</div><h1>إدارة مساعد ماركوز هوم</h1><p>سجل الدخول من لوحة التحكم أولاً.</p><a href="/admin">الذهاب لتسجيل الدخول</a></div></main>;return<KnowledgeEditor/>}

function KnowledgeEditor(){
 const[offers,setOffers]=useState<Offer[]>([]),[products,setProducts]=useState<Product[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>{const[o,p]=await Promise.all([supabase.from('assistant_offers').select('*').order('sort_order'),supabase.from('assistant_products').select('*').order('sort_order')]);if(o.data)setOffers(o.data as Offer[]);if(p.data)setProducts(p.data as Product[]);if(o.error||p.error)setNotice(`تعذر تحميل البيانات: ${o.error?.message||p.error?.message}`)};
 useEffect(()=>{load()},[]);
 const patchOffer=(id:number,patch:Partial<Offer>)=>setOffers(v=>v.map(x=>x.id===id?{...x,...patch}:x));
 const patchProduct=(id:number,patch:Partial<Product>)=>setProducts(v=>v.map(x=>x.id===id?{...x,...patch}:x));
 const saveOffer=async(o:Offer)=>{setBusy(true);setNotice('');const{error}=await supabase.from('assistant_offers').update({name_ar:o.name_ar,min_width:Number(o.min_width),max_width:o.max_width===null?null:Number(o.max_width),height_m:Number(o.height_m),price_without_installation:Number(o.price_without_installation),price_with_installation:Number(o.price_with_installation),components_ar:o.components_ar,active:o.active,sort_order:Number(o.sort_order),updated_at:new Date().toISOString()}).eq('id',o.id);setNotice(error?`تعذر الحفظ: ${error.message}`:'تم تحديث فئة المقاس بنجاح.');setBusy(false)};
 const saveProduct=async(p:Product)=>{setBusy(true);setNotice('');const{error}=await supabase.from('assistant_products').update({category_ar:p.category_ar,name_ar:p.name_ar,aliases_ar:p.aliases_ar,description_ar:p.description_ar,price_text_ar:p.price_text_ar,details_ar:p.details_ar,active:p.active,sort_order:Number(p.sort_order),updated_at:new Date().toISOString()}).eq('id',p.id);setNotice(error?`تعذر الحفظ: ${error.message}`:'تم تحديث معلومات المنتج في عقل المساعد.');setBusy(false)};
 const addProduct=async()=>{setBusy(true);const sort=products.length?Math.max(...products.map(p=>p.sort_order))+10:10;const{error}=await supabase.from('assistant_products').insert({code:`product-${Date.now()}`,category_ar:'منتج جديد',name_ar:'منتج جديد',aliases_ar:[],description_ar:'اكتب وصف المنتج',price_text_ar:'اكتب السعر',details_ar:'',active:false,sort_order:sort});if(error)setNotice(`تعذر إضافة المنتج: ${error.message}`);else{setNotice('تمت إضافة منتج جديد. عدّل بياناته ثم فعّله.');await load()}setBusy(false)};
 return <main className="admin-shell" dir="rtl"><header className="admin-header"><div><strong>عقل مساعد ماركوز هوم</strong><small>المنتجات + الأسعار + المقاسات</small></div><div><a href="/admin/overview">اللوحة الموحدة</a><a href="/" target="_blank">اختبار المساعد</a><button onClick={()=>supabase.auth.signOut().then(()=>location.href='/admin')}>تسجيل الخروج</button></div></header><div className="admin-content">
  <section className="admin-card"><div className="card-title"><div><h2>كتالوج المساعد</h2><small>أي تعديل هنا يصبح مصدر معلومات المساعد الصوتي مباشرة.</small></div><button onClick={addProduct} disabled={busy}>+ إضافة منتج</button></div>{notice&&<p className={notice.startsWith('تم')?'admin-success':'admin-error'}>{notice}</p>}</section>
  {products.map(p=><section className="admin-card assistant-admin-card" key={`p-${p.id}`}><div className="assistant-admin-grid"><label>القسم<input value={p.category_ar} onChange={e=>patchProduct(p.id,{category_ar:e.target.value})}/></label><label>اسم المنتج<input value={p.name_ar} onChange={e=>patchProduct(p.id,{name_ar:e.target.value})}/></label><label>كلمات يتعرف عليها<input value={(p.aliases_ar||[]).join('، ')} onChange={e=>patchProduct(p.id,{aliases_ar:e.target.value.split(/[،,]/).map(x=>x.trim()).filter(Boolean)})}/></label><label className="assistant-components">الوصف<textarea rows={3} value={p.description_ar} onChange={e=>patchProduct(p.id,{description_ar:e.target.value})}/></label><label className="assistant-components">السعر كما يقوله المساعد<textarea rows={2} value={p.price_text_ar} onChange={e=>patchProduct(p.id,{price_text_ar:e.target.value})}/></label><label className="assistant-components">تفاصيل إضافية<textarea rows={2} value={p.details_ar} onChange={e=>patchProduct(p.id,{details_ar:e.target.value})}/></label><label>الترتيب<input type="number" value={p.sort_order} onChange={e=>patchProduct(p.id,{sort_order:Number(e.target.value)})}/></label><label className="switch assistant-active"><input type="checkbox" checked={p.active} onChange={e=>patchProduct(p.id,{active:e.target.checked})}/><span>{p.active?'مفعّل للمساعد':'غير مفعّل'}</span></label></div><button className="assistant-save" onClick={()=>saveProduct(p)} disabled={busy}>حفظ المنتج</button></section>)}
  <section className="admin-card"><h2>فئات تسعير تصميم 198 حسب العرض</h2><small>هذه الفئات تستخدم لحساب السعر تلقائيًا عند ذكر عرض الحائط.</small></section>
  {offers.map(o=><section className="admin-card assistant-admin-card" key={`o-${o.id}`}><div className="assistant-admin-grid"><label>اسم التصميم<input value={o.name_ar} onChange={e=>patchOffer(o.id,{name_ar:e.target.value})}/></label><label>من عرض<input type="number" step="0.1" value={o.min_width} onChange={e=>patchOffer(o.id,{min_width:Number(e.target.value)})}/></label><label>إلى عرض<input type="number" step="0.1" value={o.max_width??''} onChange={e=>patchOffer(o.id,{max_width:e.target.value===''?null:Number(e.target.value)})}/></label><label>الارتفاع<input type="number" step="0.01" value={o.height_m} onChange={e=>patchOffer(o.id,{height_m:Number(e.target.value)})}/></label><label>بدون تركيب<input type="number" value={o.price_without_installation} onChange={e=>patchOffer(o.id,{price_without_installation:Number(e.target.value)})}/></label><label>مع التركيب<input type="number" value={o.price_with_installation} onChange={e=>patchOffer(o.id,{price_with_installation:Number(e.target.value)})}/></label><label className="assistant-components">المكونات<textarea rows={3} value={o.components_ar} onChange={e=>patchOffer(o.id,{components_ar:e.target.value})}/></label><label>الترتيب<input type="number" value={o.sort_order} onChange={e=>patchOffer(o.id,{sort_order:Number(e.target.value)})}/></label><label className="switch assistant-active"><input type="checkbox" checked={o.active} onChange={e=>patchOffer(o.id,{active:e.target.checked})}/><span>{o.active?'مفعّل':'غير مفعّل'}</span></label></div><button className="assistant-save" onClick={()=>saveOffer(o)} disabled={busy}>حفظ الفئة</button></section>)}
 </div></main>
}
